"""add_user_verification_columns

Revision ID: b2857505e15f
Revises: 0002_consent_paid
Create Date: 2026-06-19 23:36:11.277816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2857505e15f'
down_revision: Union[str, None] = '0002_consent_paid'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем обе колонки, которые требует твой код:
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    
    # Удаляем обе колонки при откате:
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    
    # ### end Alembic commands ###